### ISSUE TITLE
how to reproduce fig18.c?

### ISSUE THREAD

**Issue by LiYuTingxxn** [dmemsys/SMART#13]
Hello, SMART is a great job, and I am interested in it. Could you please tell me how to get sherman's result? I have tried to use "cmake -DSTATIC_MN_IP=on -DENABLE_CACHE=on -DLONG_TEST_EPOCH=off -DSHORT_TEST_EPOCH=off -DMIDDLE_TEST_EPOCH=off -DENABLE_CACHE_EVICTION=off -DON_CHIP=on .."  to run sherman, but the result is similar to SMART. How can I get the sheman's result, as the fig18c shows?  
Looking forward to your early reply. Thanks a lot!

**Comment by River861** [comment]
Hi LiYuTingxxn, thanks for your attention!

To reproduce Sherman's results, you should use our [forked Sherman repo](https://github.com/River861/Sherman.git).
We have reproduced the experiments again, and the results are correct.

If you still fail to reproduce the results, could you please describe your experimental settings and the unexpected results in detail?
Do you run the code on the  r650 machines of CloudLab? And do you change any Sherman parameters (e.g., span size,  key size, value size, number of MNs, number of clients)?
I am willing to help you.

@LiYuTingxxn

**Comment by LiYuTingxxn** [comment]
Thank you for your reply!
The Sherman repo set VALUE is uint64_t , how do you support value size >= 512B? I have set VALUE to "std::array<uint64_t,define::valLen>"(as SMART used)  in Sherman  to support variable length value, but  I failed to run  when value size >=512B. Could you pelease tell me how to support larger value size in sherman?

**Comment by River861** [comment]
Hi LiYuTingxxn, we use the `simulatedValLen` in `Common.h` to simulate value sizes larger than 8 bytes. As shown below:
https://github.com/River861/Sherman/blob/d63c224b8c2ff5b398df7a3833e53a8bea5c9f7a/include/Common.h#L126C20-L126C36

The implementation of the `Value` field is shown below:
https://github.com/River861/Sherman/blob/d63c224b8c2ff5b398df7a3833e53a8bea5c9f7a/include/Tree.h#L103-L106

Therefore, you just need to set the `simulatedValLen` to your expected value size as follows:
```c++
constexpr uint32_t simulatedValLen = 512;
```

@LiYuTingxxn

**Comment by LiYuTingxxn** [comment]
Ok, Thanks a lot!
