### ISSUE TITLE
How to implement Delete operation for SMART?

### ISSUE THREAD

**Issue by LiYuTingxxn** [dmemsys/SMART#15]
Hello, Tree.cpp doesn't provide the function "Deletion."  How can I implement it?

I look forward to your early reply. Thanks a lot!

**Comment by River861** [comment]
Hi LiYuTingxxn, sorry for the late reply.

We currently have no plan to implement the delete operation, but you can refer to the [extended version](https://dl.acm.org/doi/10.1145/3664289) of our paper, where we have provided the pseudo-code of the delete operation in ```Algorithm 3```.

Hopefully this information will help you!
@LiYuTingxxn

**Comment by LiYuTingxxn** [comment]
Thank you for reply!
