### ISSUE TITLE
Put read delegation and write combination together

### ISSUE THREAD

**Issue by minxinhao** [dmemsys/SMART#16]
Hi, Xuchuan
I still don't understand using both read delegation and write combining mechanisms at the same time.

What is the meaning of using the same time window in the paper? My understanding from the code is to extend the write combining time window from the end of the leaf lock to after the leaf unlock, i.e., to include the full tree access process just like search. But how does this mechanism allow causally related write and read operations in two threads to be assigned to two different time windows? The paper points out that the read and write clients compete for the same local lock, and I don't think I've seen any code for that.

Finally, the code uses read/write_window, r/w_lock to keep track of the corresponding time window, and only opens a new window when read/write_window is 0 at the same time (i.e., sets the corresponding read/write_window). In my understanding, a lock node's read_window and write_window can have both read and write to a key occurring at the same time, so there is still a case where causality is not guaranteed. Can you explain in more detail the consistency guarantees provided?

**Comment by River861** [comment]
Hi Xinhao, thanks for your attention!

You can refer to the [extended version](https://dl.acm.org/doi/10.1145/3664289) of our paper, where we have explained in more detail how we put things together and ensure the causality in Section 4.2.4.


Hopefully this information will help you!
@minxinhao
