### ISSUE TITLE
Error ”Send with RDMA_WRITE(WITH_IMM) failed“

### ISSUE THREAD

**Issue by MiraHyc** [dmemsys/SMART#21]
What could lead to a "Send with RDMA_WRITE(WITH_IMM) failed" error?

**Comment by MiraHyc** [comment]
And this error occured when I am running fig_18b

**Comment by MiraHyc** [comment]
And by the way, how did you look up the IOPS upper bound of your RNIC？

**Comment by River861** [comment]
Hi MiraHyc,

The RDMA_WRITE error occurring in fig_18b is quite strange, as fig_18b is a test under the YCSB C workload (100% read), which does not perform write operations. Please check your execution again.

For the second question, we evaluate the IOPS upper bound of the RNIC using the `ib_read_bw` tool. Or, you can also test it out by continuously issuing small-sized reads. 

@MiraHyc
