### ISSUE TITLE
cache problem

### ISSUE THREAD

**Issue by MiraHyc** [dmemsys/SMART#22]
When I am executing fig_18a.py and fig_17.py， these program related to the cache, it seems something went wrong. The cache hit rate seems too high （usually above 0.9) despite the change of cache size and any other variates. I wonder any reason could lead to this circumstance.

**Comment by MiraHyc** [comment]
Thank you very much. I am really interested in your new work CHIME but can not find the pdf and PPT of it. I will really appreciate it if your can send me the paper.

**Comment by River861** [comment]
Hi HiraHyc, the CHIME paper is available [here](https://doi.org/10.1145/3694715.3695959).

@MiraHyc

**Comment by MiraHyc** [comment]
Thank you very much.
&nbsp;


图明
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xuchuan ***@***.***&gt;; 
发送时间: 2024年11月16日(星期六) 中午1:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dmemsys/SMART] cache problem (Issue #22)














 
Hi HiraHyc, the CHIME paper is available here.
 
@MiraHyc
