### ISSUE TITLE
Problem about the dirID

### ISSUE THREAD

**Issue by MiraHyc** [dmemsys/SMART#24]
In the code  bindCore((CPU_PHYSICAL_CORE_NUM - 1 - dirID) * 2 + 1), why there is a multiply by 2 since CPU_PHYSICAL_CORE_NUM is already the total number of the CPU cores.

**Comment by River861** [comment]
Hi MiraHyc,

The `CPU_PHYSICAL_CORE_NUM` represents the total number of CPU cores in the NUMA node that is close to the RNIC.
We only bind clients to CPU cores that are close to the RNIC to maximize the performance.

The existing code is written for the r650 machine. In the r650 machine, there are two NUMA nodes. CPU cores with even IDs are on NUMA node 0, while those with odd IDs are on NUMA node 1. Thus, there is a "multiple by 2" in this code.
You can adjust this line of code according to your machine's CPU info (using the `lscpu` command).

@MiraHyc
