### ISSUE TITLE
I want to run the project on cloudlab and can you help me?

### ISSUE THREAD

**Issue by LBY2000** [dmemsys/SMART#6]
Hello,I appreciate your work sincerely. Now I want to run the project on cloudlab and fail to start my project on cloudlab. So can you help me and I earnestly request your assistance in conducting experiments on CloudLab.

**Comment by River861** [comment]
Hi LBY, thanks for your attention and sorry for the late reply.

Could you please describe your issues encountered on CloudLab in detail, e.g. with screenshots attached? I am willing to help you.
@LBY2000

**Comment by LBY2000** [comment]
Thanks, and the problem is solved. And now we succeed in running the project.
